export const defaultBots = [
  {
    name: "FX Pulse Basic",
    slug: "fx-pulse-basic",
    tier: "Basic",
    price: 199,
    description: "Smart trend detection bot for beginner traders.",
    features: ["AI signal engine", "Daily risk cap", "MT4 setup guide"],
    downloadUrl: "/downloads/basic-bot.zip",
    roi: 18,
    winRate: 62,
    drawdown: 7,
  },
  {
    name: "FX Pulse Pro",
    slug: "fx-pulse-pro",
    tier: "Pro",
    price: 499,
    description: "Multi-strategy AI bot optimized for aggressive growth.",
    features: ["Portfolio mode", "Auto position sizing", "Advanced logs"],
    downloadUrl: "/downloads/pro-bot.zip",
    roi: 32,
    winRate: 69,
    drawdown: 10,
  },
  {
    name: "FX Pulse Premium",
    slug: "fx-pulse-premium",
    tier: "Premium",
    price: 999,
    description: "Institution-grade AI execution with premium support.",
    features: ["High-frequency execution", "Priority support", "Private updates"],
    downloadUrl: "/downloads/premium-bot.zip",
    roi: 47,
    winRate: 74,
    drawdown: 12,
  },
] as const;

export const performanceSeries = [
  { month: "Jan", balance: 10000 },
  { month: "Feb", balance: 11120 },
  { month: "Mar", balance: 11840 },
  { month: "Apr", balance: 12760 },
  { month: "May", balance: 13620 },
  { month: "Jun", balance: 14980 },
  { month: "Jul", balance: 16110 },
  { month: "Aug", balance: 17340 },
  { month: "Sep", balance: 18620 },
  { month: "Oct", balance: 19680 },
  { month: "Nov", balance: 21150 },
  { month: "Dec", balance: 22890 },
];
